CREATE TABLE settlements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID NOT NULL,
    settlement_type VARCHAR(100) NOT NULL,
    settlement_description VARCHAR(255),
    replacement_cash_value DECIMAL(15,2) DEFAULT 0,
    recoverable_holdback DECIMAL(15,2) DEFAULT 0,
    nonrecoverable_depreciation DECIMAL(15,2) DEFAULT 0,
    actual_cash_value DECIMAL(15,2) DEFAULT 0,
    other_adjustments DECIMAL(15,2) DEFAULT 0,
    other_adjustments_description TEXT,
    deductible_applied DECIMAL(15,2) DEFAULT 0,
    net_settlement DECIMAL(15,2) DEFAULT 0,
    amount_over_policy_limit DECIMAL(15,2) DEFAULT 0,
    prior_payments DECIMAL(15,2) DEFAULT 0,
    total_settlement DECIMAL(15,2) DEFAULT 0,
    date_offered DATE,
    is_final_settlement BOOLEAN DEFAULT false,
    status VARCHAR(50) DEFAULT 'offered',
    accepted_rejected VARCHAR(20),
    rejection_reason TEXT,
    payment_expected_date DATE,
    proof_of_loss_required BOOLEAN DEFAULT false,
    notes TEXT,
    created_by UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);