CREATE TABLE vendors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    company_type VARCHAR(100) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    contact_first_name VARCHAR(100),
    contact_last_name VARCHAR(100),
    email VARCHAR(255),
    website VARCHAR(255),
    phone_1 VARCHAR(50),
    phone_2 VARCHAR(50),
    phone_3 VARCHAR(50),
    phone_4 VARCHAR(50),
    address_line_1 TEXT,
    address_line_2 TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'United States',
    is_lead_source BOOLEAN DEFAULT false,
    lead_source_owner_id UUID,
    license_number VARCHAR(100),
    insurance_info TEXT,
    w9_on_file BOOLEAN DEFAULT false,
    preferred_vendor BOOLEAN DEFAULT false,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    specialties TEXT[],
    service_areas TEXT[],
    notes TEXT,
    is_active BOOLEAN DEFAULT true,
    can_file_claim_via_email BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);