CREATE TABLE activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID,
    client_id UUID,
    activity_type VARCHAR(100) NOT NULL,
    activity_category VARCHAR(50) DEFAULT 'general',
    title VARCHAR(255) NOT NULL,
    description TEXT,
    activity_data JSONB,
    is_public BOOLEAN DEFAULT true,
    is_system_generated BOOLEAN DEFAULT false,
    communication_method VARCHAR(50),
    communication_direction VARCHAR(20),
    email_subject VARCHAR(255),
    email_from VARCHAR(255),
    email_to TEXT[],
    phone_number VARCHAR(50),
    call_duration INTEGER,
    sms_message TEXT,
    urgency VARCHAR(20) DEFAULT 'normal',
    follow_up_required BOOLEAN DEFAULT false,
    follow_up_date TIMESTAMP WITH TIME ZONE,
    created_by UUID NOT NULL,
    participants UUID[],
    related_document_ids UUID[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);