CREATE TABLE ai_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID,
    document_id UUID,
    insight_type VARCHAR(100) NOT NULL,
    insight_category VARCHAR(50),
    confidence_score DECIMAL(5,4),
    title VARCHAR(255),
    summary TEXT,
    full_analysis TEXT,
    extracted_entities JSONB,
    risk_factors JSONB,
    recommendations JSONB,
    compliance_status VARCHAR(50),
    follow_up_actions TEXT[],
    status VARCHAR(50) DEFAULT 'pending_review',
    reviewed_by UUID,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    ai_model_version VARCHAR(50),
    processing_time_ms INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);