CREATE TABLE claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    client_id UUID NOT NULL,
    property_id UUID NOT NULL,
    file_number VARCHAR(100) UNIQUE NOT NULL,
    claim_number VARCHAR(100),
    carrier_claim_number VARCHAR(100),
    carrier_id UUID,
    desk_adjuster_id UUID,
    field_adjuster_id UUID,
    assigned_adjuster_id UUID NOT NULL,
    assigned_office_staff UUID[],
    assigned_sales_staff UUID[],
    claim_status VARCHAR(50) DEFAULT 'new',
    claim_phase VARCHAR(50) DEFAULT 'initial_contact',
    priority VARCHAR(20) DEFAULT 'medium',
    date_of_loss DATE NOT NULL,
    cause_of_loss VARCHAR(100) NOT NULL,
    loss_description TEXT,
    date_reported TIMESTAMP WITH TIME ZONE,
    date_first_contact TIMESTAMP WITH TIME ZONE,
    contract_date TIMESTAMP WITH TIME ZONE,
    contract_fee_type VARCHAR(20) DEFAULT 'percentage',
    contract_fee_amount DECIMAL(10,4),
    is_claim_filed BOOLEAN DEFAULT false,
    deadline_date DATE,
    recoverable_depreciation_deadline DATE,
    is_fema_claim BOOLEAN DEFAULT false,
    is_state_emergency BOOLEAN DEFAULT false,
    emergency_name VARCHAR(255),
    reason_for_claim VARCHAR(100),
    is_home_habitable BOOLEAN,
    is_insured_living_in_home BOOLEAN,
    dwelling_damage_description TEXT,
    other_structures_damage_description TEXT,
    personal_property_damage_description TEXT,
    has_ale_expenses BOOLEAN DEFAULT false,
    has_repairs_been_done BOOLEAN DEFAULT false,
    repair_description TEXT,
    repair_type VARCHAR(50),
    repair_date DATE,
    repair_vendor VARCHAR(255),
    has_prior_claims BOOLEAN DEFAULT false,
    prior_claims_info JSONB,
    estimated_loss_value DECIMAL(15,2),
    total_settlement_amount DECIMAL(15,2),
    is_final_settlement BOOLEAN DEFAULT false,
    settlement_status VARCHAR(50) DEFAULT 'pending',
    watch_list BOOLEAN DEFAULT false,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);