CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID,
    client_id UUID,
    document_type VARCHAR(100) NOT NULL,
    document_category VARCHAR(100),
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    file_url TEXT,
    thumbnail_url TEXT,
    document_title VARCHAR(255),
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    is_confidential BOOLEAN DEFAULT false,
    folder_path TEXT,
    tags TEXT[],
    ai_extracted_text TEXT,
    ai_entities JSONB,
    ai_summary TEXT,
    ai_compliance_status VARCHAR(50),
    version_number INTEGER DEFAULT 1,
    is_signed BOOLEAN DEFAULT false,
    signed_by UUID,
    signed_at TIMESTAMP WITH TIME ZONE,
    uploaded_by UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);