CREATE TABLE insurance_carriers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    carrier_name VARCHAR(255) NOT NULL,
    carrier_code VARCHAR(50),
    email VARCHAR(255),
    website VARCHAR(255),
    phone_1 VARCHAR(50),
    phone_2 VARCHAR(50),
    fax VARCHAR(50),
    address_line_1 TEXT,
    address_line_2 TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'United States',
    claims_email VARCHAR(255),
    claims_phone VARCHAR(50),
    can_file_via_email BOOLEAN DEFAULT false,
    file_via_email_address VARCHAR(255),
    preferred_contact_method VARCHAR(50) DEFAULT 'email',
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    notes TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);