CREATE TABLE policies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID NOT NULL,
    carrier_id UUID NOT NULL,
    policy_number VARCHAR(100) NOT NULL,
    policy_type VARCHAR(100),
    policy_category VARCHAR(50),
    effective_date DATE,
    expiration_date DATE,
    total_policy_amount DECIMAL(15,2),
    dwelling_limit_a DECIMAL(15,2),
    other_structures_limit_b DECIMAL(15,2),
    contents_limit_c DECIMAL(15,2),
    loss_of_use_limit_d DECIMAL(15,2),
    ordinance_law_limit DECIMAL(15,2),
    debris_removal_limit DECIMAL(15,2),
    mold_limit DECIMAL(15,2),
    mold_limit_type VARCHAR(20) DEFAULT 'per_occurrence',
    depreciation_amount DECIMAL(15,2),
    deductible_amount DECIMAL(15,2),
    hurricane_deductible_amount DECIMAL(15,2),
    hurricane_deductible_type VARCHAR(20) DEFAULT 'amount',
    has_appraisal_clause BOOLEAN DEFAULT false,
    additional_coverages JSONB,
    policy_document_url TEXT,
    declaration_page_url TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);