CREATE TABLE properties (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    client_id UUID NOT NULL,
    property_nickname VARCHAR(255),
    property_type VARCHAR(100),
    address_line_1 TEXT NOT NULL,
    address_line_2 TEXT,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) DEFAULT 'United States',
    description TEXT,
    year_built INTEGER,
    square_footage INTEGER,
    bedrooms INTEGER,
    bathrooms INTEGER,
    stories INTEGER,
    construction_type VARCHAR(100),
    roof_type VARCHAR(100),
    heating_system VARCHAR(100),
    cooling_system VARCHAR(100),
    electrical_system VARCHAR(100),
    plumbing_system VARCHAR(100),
    foundation_type VARCHAR(100),
    garage_type VARCHAR(100),
    pool_spa BOOLEAN DEFAULT false,
    additional_structures TEXT,
    property_value DECIMAL(15,2),
    market_value DECIMAL(15,2),
    replacement_cost DECIMAL(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);