CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    claim_id UUID,
    client_id UUID,
    task_type VARCHAR(100) NOT NULL,
    task_category VARCHAR(50) DEFAULT 'general',
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    priority VARCHAR(20) DEFAULT 'medium',
    assigned_to UUID NOT NULL,
    assigned_by UUID NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE,
    completed_date TIMESTAMP WITH TIME ZONE,
    estimated_hours DECIMAL(8,2),
    actual_hours DECIMAL(8,2),
    progress_percentage INTEGER DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    is_mandatory BOOLEAN DEFAULT false,
    is_automated BOOLEAN DEFAULT false,
    automation_trigger VARCHAR(100),
    parent_task_id UUID,
    dependencies UUID[],
    checklist_items JSONB,
    notes TEXT,
    completion_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);