CREATE TABLE user_profiles (
    id UUID PRIMARY KEY,
    organization_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    middle_initial VARCHAR(5),
    phone_1 VARCHAR(50),
    phone_2 VARCHAR(50),
    phone_3 VARCHAR(50),
    phone_4 VARCHAR(50),
    address_line_1 TEXT,
    address_line_2 TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'United States',
    role VARCHAR(50) NOT NULL DEFAULT 'adjuster',
    permissions TEXT[],
    license_number VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    avatar_url TEXT,
    timezone VARCHAR(50) DEFAULT 'America/New_York',
    date_format VARCHAR(20) DEFAULT 'MM/DD/YYYY',
    notification_email BOOLEAN DEFAULT true,
    notification_sms BOOLEAN DEFAULT false,
    two_factor_enabled BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);