CREATE TABLE clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    client_type VARCHAR(50) DEFAULT 'individual',
    is_policyholder BOOLEAN DEFAULT true,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    middle_initial VARCHAR(5),
    business_name VARCHAR(255),
    title VARCHAR(100),
    nickname VARCHAR(100),
    primary_email VARCHAR(255),
    secondary_email VARCHAR(255),
    primary_phone VARCHAR(50),
    secondary_phone VARCHAR(50),
    work_phone VARCHAR(50),
    mobile_phone VARCHAR(50),
    address_line_1 TEXT,
    address_line_2 TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    country VARCHAR(100) DEFAULT 'United States',
    mailing_same_as_address BOOLEAN DEFAULT true,
    mailing_address_line_1 TEXT,
    mailing_address_line_2 TEXT,
    mailing_city VARCHAR(100),
    mailing_state VARCHAR(50),
    mailing_zip_code VARCHAR(20),
    mailing_country VARCHAR(100),
    lead_source_id UUID,
    assigned_to UUID,
    date_first_contact TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    portal_pin VARCHAR(10),
    social_media JSONB,
    employer VARCHAR(255),
    occupation VARCHAR(255),
    birthdate DATE,
    spouse_name VARCHAR(255),
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);